services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin
    user: 1000:1000
    group_add:
      - "993"
    environment:
      - JELLYFIN_CACHE_DIR=/var/cache/jellyfin
      - JELLYFIN_CONFIG_DIR=/etc/jellyfin
      - JELLYFIN_DATA_DIR=/var/lib/jellyfin
      - JELLYFIN_LOG_DIR=/var/log/jellyfin
      - TZ=America/New_York
    volumes:
      - ./configs/jellyfin/etc:/etc/jellyfin
      - ./configs/jellyfin/var-cache:/var/cache/jellyfin
      - ./configs/jellyfin/var-lib:/var/lib/jellyfin
      - ./configs/jellyfin/var-log:/var/log/jellyfin
#      - ./configs/jellyfin/timezone:/etc/timezone
      - myMedia:/mnt/servarr
    network_mode: "host"
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    restart: always
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    hostname: bazarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./configs/mediarr/bazarr:/config
      - myMedia:/mnt/servarr
    ports:
      - 6767:6767
    restart: always
    depends_on:
      - sonarr
      - radarr
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    hostname: jellyseerr
    networks:
      - mediarr
    user: 1000:1000
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    ports:
      - 5055:5055
    volumes:
      - ./configs/mediarr/jellyseerr:/app/config
    restart: always
    depends_on:
      - sonarr
      - radarr
  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    hostname: prowlarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./configs/mediarr/prowlarr:/config
    ports:
      - 9696:9696
    restart: always
    depends_on:
      - flaresolverr
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    hostname: flaresolverr
    networks:
      - mediarr
    environment:
      - LOG_LEVEL=info
    ports:
      - 8191:8191
    restart: always
  transmission-openvpn:
    cap_add:
      - NET_ADMIN
    volumes:
      - myMedia:/mnt/servarr
      - ./configs/mediarr/transmission:/config
    environment:
      - PUID=1000
      - PGID=100
      - OPENVPN_PROVIDER=PIA
      - OPENVPN_CONFIG=france
      - OPENVPN_USERNAME=p7949402
      - OPENVPN_PASSWORD=VohxtGir86
      - LOCAL_NETWORK=192.168.0.0/16
      - TRANSMISSION_DOWNLOAD_DIR=/mnt/servarr/downloads/completed
      - TRANSMISSION_INCOMPLETE_DIR=/mnt/servarr/downloads/incomplete
    logging:
      driver: json-file
      options:
        max-size: 10m
    ports:
      - '9091:9091'
    image: haugene/transmission-openvpn
    restart: always
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    hostname: radarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - ./configs/mediarr/radarr:/config
      - myMedia:/mnt/servarr
    ports:
      - 7878:7878
    restart: always
    depends_on:
      - prowlarr
      - transmission-openvpn
      - jellyfin
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    hostname: sonarr
    networks:
      - mediarr
    environment:
      - PUID=1000
      - PGID=100
    volumes:
      - ./configs/mediarr/sonarr:/config
      - myMedia:/mnt/servarr
    depends_on:
      - prowlarr
      - transmission-openvpn
      - jellyfin
    ports:
      - 8989:8989
    restart: always
networks:
  mediarr:
    driver: bridge
volumes:
  myMedia:
    driver: local
    driver_opts:
      type: nfs
      o: addr=10.0.0.2
      device: :/mnt/slurpee-1-pool/servarr
